# Generated by Django 3.2.7 on 2021-09-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_titulo', models.CharField(max_length=200)),
                ('curso_contenido', models.TextField()),
                ('curso_publicado', models.DateTimeField(verbose_name='fecha de publicacion')),
            ],
        ),
    ]
