# Generated by Django 3.2.7 on 2021-09-13 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 13, 18, 39, 32, 956725), verbose_name='fecha de publicacion'),
        ),
    ]
