# Generated by Django 3.2.7 on 2021-09-21 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210917_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 21, 18, 23, 33, 341550), verbose_name='fecha de publicacion'),
        ),
    ]
