# Generated by Django 3.2.7 on 2021-09-24 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210923_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matriculados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=200)),
                ('cedula', models.DecimalField(decimal_places=14, default=0, max_digits=15)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2021, 9, 24, 17, 38, 20, 423848), verbose_name='fecha de matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Registrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('cedula', models.DecimalField(decimal_places=14, default=0, max_digits=15)),
                ('materia', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2021, 9, 24, 17, 38, 20, 422848), verbose_name='fecha de matricula')),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 24, 17, 38, 20, 421848), verbose_name='fecha de publicacion'),
        ),
    ]
