# Generated by Django 3.2.7 on 2021-09-24 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210924_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 24, 18, 27, 47, 377834), verbose_name='fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='matriculados',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 24, 18, 27, 47, 380827), verbose_name='fecha de matricula'),
        ),
        migrations.AlterField(
            model_name='registrom',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 24, 18, 27, 47, 379828), verbose_name='fecha de matricula'),
        ),
    ]
