# Generated by Django 3.2.7 on 2021-09-24 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210924_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 24, 18, 34, 18, 718897), verbose_name='fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='matriculados',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 24, 18, 34, 18, 724894), verbose_name='fecha de matricula'),
        ),
        migrations.AlterField(
            model_name='registrom',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 24, 18, 34, 18, 720896), verbose_name='fecha de matricula'),
        ),
    ]
