# Generated by Django 3.2.7 on 2021-09-28 22:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0021_auto_20210927_1606'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matriculados',
        ),
        migrations.RemoveField(
            model_name='registrom',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='registrom',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='registrom',
            name='nombre',
        ),
        migrations.AddField(
            model_name='registrom',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrom',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.curso'),
        ),
        migrations.AddField(
            model_name='registrom',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 17, 50, 0, 662405), verbose_name='fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='registrom',
            name='cedula',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='registrom',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 17, 50, 0, 663405), verbose_name='fecha de matricula'),
        ),
    ]
