# Generated by Django 3.2.7 on 2021-10-01 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210930_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 1, 17, 56, 56, 545299), verbose_name='fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='registrom',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 1, 17, 56, 56, 548299), verbose_name='fecha de matricula'),
        ),
    ]
