# Generated by Django 3.2.7 on 2021-10-04 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20211001_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 17, 11, 0, 457175), verbose_name='fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='registrom',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 17, 11, 0, 458174), verbose_name='fecha de matricula'),
        ),
    ]
