# Generated by Django 3.2.7 on 2021-10-05 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20211004_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 15, 38, 0, 721820), verbose_name='fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='registrom',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 15, 38, 0, 723819), verbose_name='fecha de matricula'),
        ),
    ]
